/**
 * The notch's words, in the app's language (the EN / TH switch in the main
 * window; the notch follows it live). Kept here rather than in the app's
 * translations: the pill has its own short, small-space wording.
 */
import { useLanguageSettings } from "@/features/i18n";

const en = {
  home: "Home",
  ask: "Ask",
  newQuestion: "New question",
  capture: "Capture a window to ask about (or drag the bot onto it)",
  saved: "Saved",
  notSaved: "Not saved",
  savedHint: "Kept in your chats — click to stop",
  notSavedHint: "Not kept — click to keep in your chats",
  openMali: "Open Mali",
  open: "Open",
  running: "{n} running",
  greeting: "Hi, I'm {name}",
  greetingBody: "Ask me anything, drop a file here, or drag me onto a window to capture it.",
  anywhere: "anywhere",
  dragMe: "Drag me onto a window to capture it · double-click to hide",
  team: "Team",
  newBot: "New bot",
  newBotHint: "Make a bot in the app — pick a ready-made one or your own",
  noBots: "No bots yet",
  noBotsBody: "Give each bot one duty; ask it here, or let the lead hand it work.",
  askDirectly: "Ask directly",
  plan: "Plan",
  taskFinished: "Task finished",
  startWorking: "Start working…",
  working: "Working…",
  done: "Done",
  askMali: "Ask Mali",
  needsPermission: "needs permission",
  needsPermissionShort: "Needs permission",
  waiting: "+{n} waiting",
  allow: "Allow",
  deny: "Deny",
  waking: "Waking up…",
  ready: "{name} is ready · ⌥⌘M to ask",
  dropFiles: "Drop your files",
  gotIt: "Got it!",
  kinds: "PDF,Images,Code,Docs",
  placeholder: "Ask anything, or drop a file…",
  placeholderFile: "Ask about this…",
  placeholderBot: "Ask {name}…",
  placeholderFolder: "What should Mali do in {folder}?",
  placeholderSession: "Carry on with “{title}”…",
  chat: "Chat",
  attach: "Attach files",
  send: "Send",
  startWork: "Start working",
  writing: "Writing the answer…",
  // What a run made
  pictures: "Pictures",
  onePage: "1 page",
  pages: "{n} pages",
  openIn: "Open in {app}",
  noPreview: "No preview",
  previewExpired: "Link expired — open in",
  close: "Close",
  previous: "Previous",
  next: "Next",
  madeIt: "Done — have a look",
  more: "+{n} more in Mali",
  stop: "Stop",
  thinking: "Thinking…",
  voiceListening: "Listening…",
  voiceHint: "Pause and it sends",
  voiceHintManual: "Tap ✓ when you're done",
  voiceWriting: "Writing it down…",
  voiceSpeak: "Speak a task",
  voiceDone: "Done",
  voiceCancel: "Cancel",
  voiceSpeaking: "Speaking",
  voicePreparing: "Getting the voice ready…",
  voiceThinking: "Thinking… I'll answer out loud",
  voiceStop: "Stop",
  stopped: "Stopped",
  checkingFolder: "Checking the folder…",
  queued: "Queued — another task is working in this folder",
  starting: "Starting…",
  waitingOk: "Waiting for your OK above",
  filesChanged: "{n} files changed",
  fileChanged: "1 file changed",
  reviewUndo: "Review & undo in Mali",
  openInMali: "Open in Mali",
  answeringWith: "Answering with {name} — click to change",
  remove: "Remove",
  captured: "Captured",
  askMaliInstead: "Ask Mali instead",
  // One tap after a capture or a file.
  qExplain: "Explain",
  qExplainPrompt: "Explain what's in this, simply.",
  qSummarize: "Summarize",
  qSummarizePrompt: "Summarize the key points of this in a few short bullets.",
  qIssues: "Find issues",
  qIssuesPrompt: "Look for anything wrong or off in this, and say how to fix it.",
  qContinue: "Continue",
  qContinuePrompt: "Carry on with this work and finish it.",
  // Folders
  foldersIntro: "Work in a folder, like Cowork: Mali can read and change files there. Each run can be undone in the app.",
  chatOnly: "Chat only",
  noFiles: "no files",
  readWrite: "read & write",
  readOnly: "read only",
  chooseFolder: "Choose a folder…",
  // Models
  searchModels: "Search models…",
  sameAs: "Same as {where} · {name}",
  quickBar: "Quick bar",
  cowork: "Cowork",
  coworksModel: "Cowork's model",
  quickBarSettings: "Settings → Quick bar",
  all: "All",
  addKey: "Add a key in the app",
  signIn: "Sign in in the app",
  pickFolder: "Pick a folder",
  free: "Free",
  noMatch: "No model matches “{q}”.",
  noModels: "Nothing here yet — sign in to a CLI or add a key in the app.",
  // Sessions
  sessions: "Sessions",
  sessionsHint: "Tap one to carry on here",
  noSessions: "No chats yet",
  noSessionsBody: "Ask something here or in the app; it shows up here to pick up again.",
  you: "You",
  untitled: "Untitled",
  code: "Code",
  continuing: "Continuing “{title}”",
  leaveSession: "Back to a new question",
  earlier: "Earlier",
  // Home
  needsYou: "needs you",
  failedShort: "didn't finish",
  workingShort: "working",
  askName: "Ask {name}",
  onIt: "on it",
  lead: "lead",
  standingBy: "standing by",
  teamBusy: "{n} working · {free} free",
  teamFree: "All free — tap to see them",
  // Peeks
  peekFinished: "{name} finished",
  peekFailed: "{name} couldn't finish",
  peekTakesOver: "{name} takes over",
  peekEdited: "{name} edited a file",
  peekCreated: "{name} made a file",
  peekChanged: "{n} files changed",
  // Composer
  composerHint: "Enter to send · Shift+Enter new line · Esc to close",
  // Home's pages
  usageTitle: "Cowork today",
  usageRuns: "runs",
  usageTime: "worked",
  usageFiles: "files",
  usageWeek: "Runs, last 7 days",
  quickSettings: "Settings",
  lookLabel: "Look",
  lookBlack: "Black",
  lookGlass: "Glass",
  lookLight: "Light",
  saveChats: "Save chats",
  screenLabel: "Screen",
  screenFollow: "Follow",
  screenMac: "Mac",
  screenMain: "Main",
  recapTitle: "Weekly recap",
  recapNone: "Nothing this week.",
  thisWeek: "This week",
  lastWeek: "Last week",
  weeksAgo: "{n} weeks ago",
  previousWeek: "Previous week",
  nextWeek: "Next week",
  seeWeek: "See the whole week",
  timeSaved: "Time saved (estimate)",
  savedLine: "{tasks} tasks · {created} files created · {edited} edited · {commands} commands",
  recapLineShort: "{tasks} tasks · {files} files",
  hoursMinutes: "{h} hr {m} min",
  minutesOnly: "{m} min",
  tileTasks: "Tasks",
  tileChats: "in {n} chats",
  tileFiles: "Files",
  filesSub: "{created} new · {edited} edited",
  agentTime: "Agent time",
  commandsSub: "{n} commands",
  costLabel: "Cost",
  tokensSub: "{n} tokens",
  modelsLabel: "Models",
  modelTasks: "{n} tasks",
  recapFoot: "Time saved is estimated from the files and commands each task handled.",
  adjustEstimate: "Adjust the estimate",
  rateTask: "min/task",
  rateCreated: "/new file",
  rateEdited: "/edit",
  rateCommand: "/command",
  // The agent's question
  asks: "{name} asks",
  questionStep: "{n} of {total}",
  pickOne: "Pick one",
  pickAny: "Pick any",
  orWrite: "Or write your own…",
  typeAnswer: "Type your answer…",
  skip: "Skip",
  skipHint: "Skip — let the agent decide",
  back: "Back",
  sendAnswer: "Send",
  keysHint: "1–{n} to pick",
  waitingAnswer: "Waiting for your answer",
  hasQuestion: "Has a question for you",
  askingYou: "Asking you",
};

type Key = keyof typeof en;

const th: Record<Key, string> = {
  home: "หน้าแรก",
  ask: "ถาม",
  newQuestion: "คำถามใหม่",
  capture: "จับภาพหน้าต่างเพื่อถาม (หรือลากน้องบอตไปวางบนหน้าต่าง)",
  saved: "บันทึก",
  notSaved: "ไม่บันทึก",
  savedHint: "เก็บไว้ในแชท — กดเพื่อเลิกเก็บ",
  notSavedHint: "ไม่เก็บไว้ — กดเพื่อเก็บในแชท",
  openMali: "เปิด Mali",
  open: "เปิด",
  running: "ทำอยู่ {n} งาน",
  greeting: "สวัสดี ฉันคือ {name}",
  greetingBody: "ถามอะไรก็ได้ วางไฟล์ที่นี่ หรือลากฉันไปวางบนหน้าต่างเพื่อจับภาพ",
  anywhere: "ได้ทุกที่",
  dragMe: "ลากฉันไปวางบนหน้าต่างเพื่อจับภาพ · ดับเบิลคลิกเพื่อซ่อน",
  team: "ทีม",
  newBot: "เพิ่มบอต",
  newBotHint: "สร้างบอตในแอป — เลือกแบบสำเร็จรูปหรือสร้างเอง",
  noBots: "ยังไม่มีบอต",
  noBotsBody: "ให้บอตแต่ละตัวมีหน้าที่เดียว ถามได้ที่นี่ หรือให้หัวหน้าส่งงานให้",
  askDirectly: "ถามได้โดยตรง",
  plan: "แผนงาน",
  taskFinished: "เสร็จแล้ว",
  startWorking: "เริ่มทำงาน…",
  working: "กำลังทำงาน…",
  done: "เสร็จแล้ว",
  askMali: "ถาม Mali",
  needsPermission: "ขออนุญาต",
  needsPermissionShort: "รออนุญาต",
  waiting: "รออีก {n}",
  allow: "อนุญาต",
  deny: "ไม่อนุญาต",
  waking: "กำลังตื่น…",
  ready: "{name} พร้อมแล้ว · กด ⌥⌘M เพื่อถาม",
  dropFiles: "วางไฟล์ที่นี่",
  gotIt: "ได้แล้ว!",
  kinds: "PDF,รูปภาพ,โค้ด,เอกสาร",
  placeholder: "ถามอะไรก็ได้ หรือวางไฟล์…",
  placeholderFile: "ถามเกี่ยวกับสิ่งนี้…",
  placeholderBot: "ถาม {name}…",
  placeholderFolder: "ให้ Mali ทำอะไรใน {folder}?",
  placeholderSession: "คุยต่อใน “{title}”…",
  chat: "แชท",
  attach: "แนบไฟล์",
  send: "ส่ง",
  startWork: "เริ่มทำงาน",
  writing: "กำลังเขียนคำตอบ…",
  pictures: "รูปภาพ",
  onePage: "1 หน้า",
  pages: "{n} หน้า",
  openIn: "เปิดใน {app}",
  noPreview: "ดูตัวอย่างไม่ได้",
  previewExpired: "ลิงก์หมดอายุ — เปิดใน",
  close: "ปิด",
  previous: "ก่อนหน้า",
  next: "ถัดไป",
  madeIt: "เสร็จแล้ว — ดูผลงานได้เลย",
  more: "อีก {n} ชิ้นใน Mali",
  stop: "หยุด",
  thinking: "กำลังคิด…",
  voiceListening: "กำลังฟัง…",
  voiceHint: "หยุดพูดแล้วส่งให้เอง",
  voiceHintManual: "พูดจบแล้วแตะ ✓",
  voiceWriting: "กำลังถอดเสียง…",
  voiceSpeak: "พูดสั่งงาน",
  voiceDone: "เสร็จ",
  voiceCancel: "ยกเลิก",
  voiceSpeaking: "กำลังพูด",
  voicePreparing: "กำลังเตรียมเสียง…",
  voiceThinking: "กำลังคิด… เดี๋ยวตอบเป็นเสียง",
  voiceStop: "หยุด",
  stopped: "หยุดแล้ว",
  checkingFolder: "กำลังเช็กโฟลเดอร์…",
  queued: "รอคิว — มีงานอื่นใช้โฟลเดอร์นี้อยู่",
  starting: "กำลังเริ่ม…",
  waitingOk: "รอคุณกดอนุญาตด้านบน",
  filesChanged: "แก้ {n} ไฟล์",
  fileChanged: "แก้ 1 ไฟล์",
  reviewUndo: "ดูและย้อนกลับใน Mali",
  openInMali: "เปิดใน Mali",
  answeringWith: "ตอบด้วย {name} — กดเพื่อเปลี่ยน",
  remove: "เอาออก",
  captured: "จับภาพแล้ว",
  askMaliInstead: "ถาม Mali แทน",
  qExplain: "อธิบาย",
  qExplainPrompt: "อธิบายสิ่งที่อยู่ในนี้ให้เข้าใจง่าย",
  qSummarize: "สรุป",
  qSummarizePrompt: "สรุปใจความสำคัญจากสิ่งนี้เป็นข้อ ๆ สั้น ๆ",
  qIssues: "หาจุดผิด",
  qIssuesPrompt: "ดูว่ามีปัญหาหรือจุดที่ผิดตรงไหน แล้วบอกวิธีแก้",
  qContinue: "ทำต่อ",
  qContinuePrompt: "ทำงานนี้ต่อให้เสร็จ",
  foldersIntro: "ทำงานในโฟลเดอร์แบบ Cowork: Mali อ่านและแก้ไฟล์ในนั้นได้ ทุกครั้งย้อนกลับได้ในแอป",
  chatOnly: "แชทอย่างเดียว",
  noFiles: "ไม่แตะไฟล์",
  readWrite: "อ่านและแก้ได้",
  readOnly: "อ่านอย่างเดียว",
  chooseFolder: "เลือกโฟลเดอร์…",
  searchModels: "ค้นหาโมเดล…",
  sameAs: "เหมือน {where} · {name}",
  quickBar: "Quick bar",
  cowork: "Cowork",
  coworksModel: "โมเดลของ Cowork",
  quickBarSettings: "ตั้งค่า → Quick bar",
  all: "ทั้งหมด",
  addKey: "ใส่คีย์ในแอปก่อน",
  signIn: "ล็อกอินในแอปก่อน",
  pickFolder: "เลือกโฟลเดอร์ก่อน",
  free: "ฟรี",
  noMatch: "ไม่มีโมเดลที่ตรงกับ “{q}”",
  noModels: "ยังไม่มี — ล็อกอิน CLI หรือใส่คีย์ในแอปก่อน",
  sessions: "เซสชัน",
  sessionsHint: "กดเพื่อคุยต่อตรงนี้",
  noSessions: "ยังไม่มีแชท",
  noSessionsBody: "ถามที่นี่หรือในแอป แล้วจะมาอยู่ตรงนี้ให้คุยต่อได้",
  you: "คุณ",
  untitled: "ไม่มีชื่อ",
  code: "โค้ด",
  continuing: "คุยต่อใน “{title}”",
  leaveSession: "กลับไปถามเรื่องใหม่",
  earlier: "ก่อนหน้า",
  needsYou: "รอคุณอยู่",
  failedShort: "ทำไม่สำเร็จ",
  workingShort: "กำลังทำ",
  askName: "ถาม {name}",
  onIt: "กำลังทำ",
  lead: "หัวหน้า",
  standingBy: "รออยู่",
  teamBusy: "ทำอยู่ {n} · ว่าง {free}",
  teamFree: "ว่างทุกตัว — กดเพื่อดู",
  peekFinished: "{name} ทำเสร็จแล้ว",
  peekFailed: "{name} ทำไม่สำเร็จ",
  peekTakesOver: "{name} รับงานต่อ",
  peekEdited: "{name} แก้ไฟล์",
  peekCreated: "{name} สร้างไฟล์",
  peekChanged: "แก้ {n} ไฟล์",
  composerHint: "Enter ส่ง · Shift+Enter ขึ้นบรรทัด · Esc ปิด",
  usageTitle: "Cowork วันนี้",
  usageRuns: "งาน",
  usageTime: "เวลาทำงาน",
  usageFiles: "ไฟล์",
  usageWeek: "จำนวนงาน 7 วันล่าสุด",
  quickSettings: "ตั้งค่า",
  lookLabel: "หน้าตา",
  lookBlack: "ดำ",
  lookGlass: "กระจก",
  lookLight: "สว่าง",
  saveChats: "บันทึกแชท",
  screenLabel: "จอ",
  screenFollow: "ตามเมาส์",
  screenMac: "Mac",
  screenMain: "จอหลัก",
  recapTitle: "สรุปประจำสัปดาห์",
  recapNone: "สัปดาห์นี้ยังไม่มีงาน",
  thisWeek: "สัปดาห์นี้",
  lastWeek: "สัปดาห์ที่แล้ว",
  weeksAgo: "{n} สัปดาห์ก่อน",
  previousWeek: "สัปดาห์ก่อนหน้า",
  nextWeek: "สัปดาห์ถัดไป",
  seeWeek: "ดูสรุปทั้งสัปดาห์",
  timeSaved: "เวลาที่ประหยัดได้ (ประมาณ)",
  savedLine: "{tasks} งาน · สร้าง {created} ไฟล์ · แก้ {edited} · รัน {commands} คำสั่ง",
  recapLineShort: "{tasks} งาน · {files} ไฟล์",
  hoursMinutes: "{h} ชม. {m} นาที",
  minutesOnly: "{m} นาที",
  tileTasks: "งาน",
  tileChats: "ใน {n} แชท",
  tileFiles: "ไฟล์",
  filesSub: "ใหม่ {created} · แก้ {edited}",
  agentTime: "เวลาของ agent",
  commandsSub: "{n} คำสั่ง",
  costLabel: "ค่าใช้จ่าย",
  tokensSub: "{n} โทเค็น",
  modelsLabel: "โมเดล",
  modelTasks: "{n} งาน",
  recapFoot: "เวลาที่ประหยัดได้ประมาณจากไฟล์และคำสั่งที่แต่ละงานทำ",
  adjustEstimate: "ปรับการประมาณ",
  rateTask: "นาที/งาน",
  rateCreated: "/ไฟล์ใหม่",
  rateEdited: "/ไฟล์ที่แก้",
  rateCommand: "/คำสั่ง",
  asks: "{name} ถาม",
  questionStep: "ข้อ {n}/{total}",
  pickOne: "เลือก 1 ข้อ",
  pickAny: "เลือกได้หลายข้อ",
  orWrite: "หรือพิมพ์คำตอบเอง…",
  typeAnswer: "พิมพ์คำตอบ…",
  skip: "ข้าม",
  skipHint: "ข้าม — ให้ agent ตัดสินใจเอง",
  back: "ย้อนกลับ",
  sendAnswer: "ส่งคำตอบ",
  keysHint: "กด 1–{n} เพื่อเลือก",
  waitingAnswer: "รอคำตอบจากคุณ",
  hasQuestion: "มีคำถามถึงคุณ",
  askingYou: "ถามคุณอยู่",
};

export type NotchText = (key: Key, params?: Record<string, string | number>) => string;

function fill(text: string, params?: Record<string, string | number>) {
  return params ? text.replace(/\{(\w+)\}/g, (_, name) => String(params[name] ?? "")) : text;
}

export function useNotchText(): NotchText {
  const { current } = useLanguageSettings();
  const words = current === "th" ? th : en;
  return (key, params) => fill(words[key], params);
}
