/**
 * The notch's words, in the app's language (the EN / TH switch in the main
 * window; the notch follows it live). Kept here rather than in the app's
 * translations: the pill has its own short, small-space wording.
 */
import { useLanguageSettings } from "@/features/i18n";

const en = {
  home: "Home",
  ask: "Ask",
  newQuestion: "New question",
  capture: "Capture a window to ask about (or drag the bot onto it)",
  saved: "Saved",
  notSaved: "Not saved",
  savedHint: "Kept in your chats — click to stop",
  notSavedHint: "Not kept — click to keep in your chats",
  openMali: "Open Mali",
  open: "Open",
  running: "{n} running",
  greeting: "Hi, I'm {name}",
  greetingBody: "Ask me anything, drop a file here, or drag me onto a window to capture it.",
  anywhere: "anywhere",
  dragMe: "Drag me onto a window to capture it · double-click to hide",
  team: "Team",
  newBot: "New bot",
  newBotHint: "Make a bot in the app — pick a ready-made one or your own",
  noBots: "No bots yet",
  noBotsBody: "Give each bot one duty; ask it here, or let the lead hand it work.",
  askDirectly: "Ask directly",
  plan: "Plan",
  taskFinished: "Task finished",
  startWorking: "Start working…",
  working: "Working…",
  done: "Done",
  askMali: "Ask Mali",
  needsPermission: "needs permission",
  needsPermissionShort: "Needs permission",
  waiting: "+{n} waiting",
  allow: "Allow",
  deny: "Deny",
  waking: "Waking up…",
  ready: "{name} is ready · ⌥⌘M to ask",
  dropFiles: "Drop your files",
  gotIt: "Got it!",
  kinds: "PDF,Images,Code,Docs",
  placeholder: "Ask anything, or drop a file…",
  placeholderFile: "Ask about this…",
  placeholderBot: "Ask {name}…",
  placeholderFolder: "What should Mali do in {folder}?",
  chat: "Chat",
  attach: "Attach files",
  send: "Send",
  startWork: "Start working",
  stop: "Stop",
  thinking: "Thinking…",
  stopped: "Stopped",
  checkingFolder: "Checking the folder…",
  queued: "Queued — another task is working in this folder",
  starting: "Starting…",
  waitingOk: "Waiting for your OK above",
  filesChanged: "{n} files changed",
  fileChanged: "1 file changed",
  reviewUndo: "Review & undo in Mali",
  openInMali: "Open in Mali",
  answeringWith: "Answering with {name} — click to change",
  remove: "Remove",
  captured: "Captured",
  askMaliInstead: "Ask Mali instead",
  // One tap after a capture or a file.
  qExplain: "Explain",
  qExplainPrompt: "Explain what's in this, simply.",
  qSummarize: "Summarize",
  qSummarizePrompt: "Summarize the key points of this in a few short bullets.",
  qIssues: "Find issues",
  qIssuesPrompt: "Look for anything wrong or off in this, and say how to fix it.",
  qContinue: "Continue",
  qContinuePrompt: "Carry on with this work and finish it.",
  // Folders
  foldersIntro: "Work in a folder, like Cowork: Mali can read and change files there. Each run can be undone in the app.",
  chatOnly: "Chat only",
  noFiles: "no files",
  readWrite: "read & write",
  readOnly: "read only",
  chooseFolder: "Choose a folder…",
  // Models
  searchModels: "Search models…",
  sameAs: "Same as {where} · {name}",
  quickBar: "Quick bar",
  cowork: "Cowork",
  coworksModel: "Cowork's model",
  quickBarSettings: "Settings → Quick bar",
  all: "All",
  addKey: "Add a key in the app",
  signIn: "Sign in in the app",
  pickFolder: "Pick a folder",
  free: "Free",
  noMatch: "No model matches “{q}”.",
  noModels: "Nothing here yet — sign in to a CLI or add a key in the app.",
};

type Key = keyof typeof en;

const th: Record<Key, string> = {
  home: "หน้าแรก",
  ask: "ถาม",
  newQuestion: "คำถามใหม่",
  capture: "จับภาพหน้าต่างเพื่อถาม (หรือลากน้องบอตไปวางบนหน้าต่าง)",
  saved: "บันทึก",
  notSaved: "ไม่บันทึก",
  savedHint: "เก็บไว้ในแชท — กดเพื่อเลิกเก็บ",
  notSavedHint: "ไม่เก็บไว้ — กดเพื่อเก็บในแชท",
  openMali: "เปิด Mali",
  open: "เปิด",
  running: "ทำอยู่ {n} งาน",
  greeting: "สวัสดี ฉันคือ {name}",
  greetingBody: "ถามอะไรก็ได้ วางไฟล์ที่นี่ หรือลากฉันไปวางบนหน้าต่างเพื่อจับภาพ",
  anywhere: "ได้ทุกที่",
  dragMe: "ลากฉันไปวางบนหน้าต่างเพื่อจับภาพ · ดับเบิลคลิกเพื่อซ่อน",
  team: "ทีม",
  newBot: "เพิ่มบอต",
  newBotHint: "สร้างบอตในแอป — เลือกแบบสำเร็จรูปหรือสร้างเอง",
  noBots: "ยังไม่มีบอต",
  noBotsBody: "ให้บอตแต่ละตัวมีหน้าที่เดียว ถามได้ที่นี่ หรือให้หัวหน้าส่งงานให้",
  askDirectly: "ถามได้โดยตรง",
  plan: "แผนงาน",
  taskFinished: "เสร็จแล้ว",
  startWorking: "เริ่มทำงาน…",
  working: "กำลังทำงาน…",
  done: "เสร็จแล้ว",
  askMali: "ถาม Mali",
  needsPermission: "ขออนุญาต",
  needsPermissionShort: "รออนุญาต",
  waiting: "รออีก {n}",
  allow: "อนุญาต",
  deny: "ไม่อนุญาต",
  waking: "กำลังตื่น…",
  ready: "{name} พร้อมแล้ว · กด ⌥⌘M เพื่อถาม",
  dropFiles: "วางไฟล์ที่นี่",
  gotIt: "ได้แล้ว!",
  kinds: "PDF,รูปภาพ,โค้ด,เอกสาร",
  placeholder: "ถามอะไรก็ได้ หรือวางไฟล์…",
  placeholderFile: "ถามเกี่ยวกับสิ่งนี้…",
  placeholderBot: "ถาม {name}…",
  placeholderFolder: "ให้ Mali ทำอะไรใน {folder}?",
  chat: "แชท",
  attach: "แนบไฟล์",
  send: "ส่ง",
  startWork: "เริ่มทำงาน",
  stop: "หยุด",
  thinking: "กำลังคิด…",
  stopped: "หยุดแล้ว",
  checkingFolder: "กำลังเช็กโฟลเดอร์…",
  queued: "รอคิว — มีงานอื่นใช้โฟลเดอร์นี้อยู่",
  starting: "กำลังเริ่ม…",
  waitingOk: "รอคุณกดอนุญาตด้านบน",
  filesChanged: "แก้ {n} ไฟล์",
  fileChanged: "แก้ 1 ไฟล์",
  reviewUndo: "ดูและย้อนกลับใน Mali",
  openInMali: "เปิดใน Mali",
  answeringWith: "ตอบด้วย {name} — กดเพื่อเปลี่ยน",
  remove: "เอาออก",
  captured: "จับภาพแล้ว",
  askMaliInstead: "ถาม Mali แทน",
  qExplain: "อธิบาย",
  qExplainPrompt: "อธิบายสิ่งที่อยู่ในนี้ให้เข้าใจง่าย",
  qSummarize: "สรุป",
  qSummarizePrompt: "สรุปใจความสำคัญจากสิ่งนี้เป็นข้อ ๆ สั้น ๆ",
  qIssues: "หาจุดผิด",
  qIssuesPrompt: "ดูว่ามีปัญหาหรือจุดที่ผิดตรงไหน แล้วบอกวิธีแก้",
  qContinue: "ทำต่อ",
  qContinuePrompt: "ทำงานนี้ต่อให้เสร็จ",
  foldersIntro: "ทำงานในโฟลเดอร์แบบ Cowork: Mali อ่านและแก้ไฟล์ในนั้นได้ ทุกครั้งย้อนกลับได้ในแอป",
  chatOnly: "แชทอย่างเดียว",
  noFiles: "ไม่แตะไฟล์",
  readWrite: "อ่านและแก้ได้",
  readOnly: "อ่านอย่างเดียว",
  chooseFolder: "เลือกโฟลเดอร์…",
  searchModels: "ค้นหาโมเดล…",
  sameAs: "เหมือน {where} · {name}",
  quickBar: "Quick bar",
  cowork: "Cowork",
  coworksModel: "โมเดลของ Cowork",
  quickBarSettings: "ตั้งค่า → Quick bar",
  all: "ทั้งหมด",
  addKey: "ใส่คีย์ในแอปก่อน",
  signIn: "ล็อกอินในแอปก่อน",
  pickFolder: "เลือกโฟลเดอร์ก่อน",
  free: "ฟรี",
  noMatch: "ไม่มีโมเดลที่ตรงกับ “{q}”",
  noModels: "ยังไม่มี — ล็อกอิน CLI หรือใส่คีย์ในแอปก่อน",
};

export type NotchText = (key: Key, params?: Record<string, string | number>) => string;

function fill(text: string, params?: Record<string, string | number>) {
  return params ? text.replace(/\{(\w+)\}/g, (_, name) => String(params[name] ?? "")) : text;
}

export function useNotchText(): NotchText {
  const { current } = useLanguageSettings();
  const words = current === "th" ? th : en;
  return (key, params) => fill(words[key], params);
}
